-- AlterTable
ALTER TABLE "admin" ALTER COLUMN "avatarUrl" DROP NOT NULL,
ALTER COLUMN "dateOfBirth" DROP NOT NULL,
ALTER COLUMN "gender" SET DEFAULT 'MALE',
ALTER COLUMN "contactNo" DROP NOT NULL,
ALTER COLUMN "presentAddress" DROP NOT NULL,
ALTER COLUMN "permanentAddress" DROP NOT NULL,
ALTER COLUMN "occupation" DROP NOT NULL,
ALTER COLUMN "designation" DROP NOT NULL,
ALTER COLUMN "bloodGroup" DROP NOT NULL;

-- AlterTable
ALTER TABLE "buyer" ALTER COLUMN "avatarUrl" DROP NOT NULL,
ALTER COLUMN "dateOfBirth" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "contactNo" DROP NOT NULL,
ALTER COLUMN "presentAddress" DROP NOT NULL,
ALTER COLUMN "permanentAddress" DROP NOT NULL,
ALTER COLUMN "occupation" DROP NOT NULL,
ALTER COLUMN "bloodGroup" DROP NOT NULL;

-- AlterTable
ALTER TABLE "order_item" ADD COLUMN     "price" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "seller" ALTER COLUMN "avatarUrl" DROP NOT NULL,
ALTER COLUMN "dateOfBirth" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "gender" SET DEFAULT 'MALE',
ALTER COLUMN "contactNo" DROP NOT NULL,
ALTER COLUMN "presentAddress" DROP NOT NULL,
ALTER COLUMN "permanentAddress" DROP NOT NULL,
ALTER COLUMN "occupation" DROP NOT NULL,
ALTER COLUMN "bloodGroup" DROP NOT NULL;
